### ISSUE TITLE
As a Data Analyst I want to produce a report of the top N populated cities in a continent where I provide N, so that I can observe, analyse and deliver data about the top N populated cities in continent.

### ISSUE THREAD

**Issue by Nasran-M** [Nasran-M/improved-lamp#14]

**Comment by Nasran-M** [comment]
![Top3CitiesContinent](https://user-images.githubusercontent.com/98288697/165440339-83c689df-1453-46b0-9a90-d2a306831040.png)

**Comment by GGNsw** [comment]
![image](https://user-images.githubusercontent.com/85527717/165497100-a84580e9-9df7-441c-98a9-8669bdeebd70.png)
