### ISSUE TITLE
As a Data Analyst I want to produce a report of the top N populated cities in a region where I provide N, so that I can observe, analyse and deliver data about the top N populated cities in a region.

### ISSUE THREAD

**Issue by Nasran-M** [Nasran-M/improved-lamp#15]

**Comment by Nasran-M** [comment]
![Top3CitiesRegion](https://user-images.githubusercontent.com/98288697/165418047-845a94c6-2d71-43a7-bd3a-8c340620c7e3.png)

**Comment by Nasran-M** [comment]
![Top3CitiesRegion](https://user-images.githubusercontent.com/98288697/165440448-8b9336d2-b223-4274-a8e0-b6fcdaf4a11f.png)

**Comment by GGNsw** [comment]
![image](https://user-images.githubusercontent.com/85527717/165497282-eb47c443-4eb8-462a-bbb0-40e0de11c2fb.png)
