### ISSUE TITLE
As a Data Analyst I want to produce a report of the top N populated cities in a district where I provide N, so that I can observe, analyse and deliver data about the top N populated cities in a district.

### ISSUE THREAD

**Issue by Nasran-M** [Nasran-M/improved-lamp#17]

**Comment by Nasran-M** [comment]
![Top3CitiesDistrict](https://user-images.githubusercontent.com/98288697/165417983-9b914e03-2d0a-481c-865b-f1e276503b25.png)

**Comment by Nasran-M** [comment]
![Top3CitiesDistrict](https://user-images.githubusercontent.com/98288697/165441496-31c1bc95-a46b-4273-8aae-b1dce9cd0889.png)

**Comment by GGNsw** [comment]
![image](https://user-images.githubusercontent.com/85527717/165497420-d961f4f6-55b6-41a4-a7e9-0e76ece88711.png)
